name: threeway
description: "Una billetera para gestionar tus finanzas personales dividiendo tus gastos en Necesidades, Deseos y Ahorro."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  google_fonts: ^6.3.3
  intl: ^0.20.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  fl_chart: ^1.1.1
  path: ^1.9.0
  sqflite_common_ffi_web: ^1.0.2
  sqflite_common_ffi: ^2.3.6
  percent_indicator: ^4.2.5
  pinput: ^6.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/images/
    - assets/images/image.webp
